workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 11
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Force Gradle 7.6.1 to match AGP 7.4.2
        script: |
          cd android
          gradle wrapper --gradle-version 7.6.1
          cd ..
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Generate Isar models
        script: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: flutter build apk --release -v
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
