workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build Android APK (debug)
        script: flutter build apk --debug --no-pub -v
      - name: Build Android App Bundle (debug)
        script: flutter build appbundle --debug --no-pub -v
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
      - build/app/outputs/bundle/**/*.aab
