package com.eyeguard.pro;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    // Custom plugins are registered automatically via Flutter plugin system
    // AutostartPlugin and FilterPlugin are registered via pubspec.yaml
  }
}
